name: Fetch Weibo Hot (write real data)

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch top 20 from TianAPI and write REAL data
        run: |
          curl -s "https://apis.tianapi.com/weibohot/index?key=${{ secrets.TIANAPI_KEY }}&num=20" -o hot.json
          # 可加一行校验返回码是否为200

      - name: Commit & push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add hot.json
            git commit -m "chore: update hot.json [skip ci]"
            git push
          fi
